{
  "schema_version": "1.4.0",
  "id": "GHSA-r6qv-92wg-r8qx",
  "modified": "2024-04-04T02:47:08Z",
  "published": "2022-05-24T17:07:28Z",
  "aliases": [
    "CVE-2019-20432"
  ],
  "details": "In the Lustre file system before 2.12.3, the mdt module has an out-of-bounds access and panic due to the lack of validation for specific fields of packets sent by a client. mdt_file_secctx_unpack does not validate the value of name_size derived from req_capsule_get_size.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-20432"
    },
    {
      "type": "WEB",
      "url": "https://jira.whamcloud.com/browse/LU-12604"
    },
    {
      "type": "WEB",
      "url": "https://review.whamcloud.com/#/c/35868"
    },
    {
      "type": "WEB",
      "url": "http://lustre.org"
    },
    {
      "type": "WEB",
      "url": "http://wiki.lustre.org/Lustre_2.12.3_Changelog"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-787"
    ],
    "severity": "HIGH",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2020-01-27T05:15:00Z"
  }
}