{
  "schema_version": "1.4.0",
  "id": "GHSA-r3r2-rv2r-78wf",
  "modified": "2023-01-24T03:30:17Z",
  "published": "2022-05-24T17:25:04Z",
  "aliases": [
    "CVE-2020-15701"
  ],
  "details": "An unhandled exception in check_ignored() in apport/report.py can be exploited by a local attacker to cause a denial of service. If the mtime attribute is a string value in apport-ignore.xml, it will trigger an unhandled exception, resulting in a crash. Fixed in 2.20.1-0ubuntu2.24, 2.20.9-0ubuntu7.16, 2.20.11-0ubuntu27.6.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-15701"
    },
    {
      "type": "WEB",
      "url": "https://launchpad.net/bugs/1877023"
    },
    {
      "type": "WEB",
      "url": "https://usn.ubuntu.com/4449-1"
    },
    {
      "type": "WEB",
      "url": "https://usn.ubuntu.com/4449-2"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-755"
    ],
    "severity": "LOW",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2020-08-06T23:15:00Z"
  }
}