{
  "schema_version": "1.4.0",
  "id": "GHSA-gpgf-w78r-4pvj",
  "modified": "2024-03-27T18:32:38Z",
  "published": "2022-11-22T03:30:56Z",
  "aliases": [
    "CVE-2022-36227"
  ],
  "details": "In libarchive 3.6.1, the software does not check for an error after calling calloc function that can return with a NULL pointer if the function fails, which leads to a resultant NULL pointer dereference or, in some cases, even arbitrary code execution.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-36227"
    },
    {
      "type": "WEB",
      "url": "https://github.com/libarchive/libarchive/issues/1754"
    },
    {
      "type": "WEB",
      "url": "https://bugs.gentoo.org/882521"
    },
    {
      "type": "WEB",
      "url": "https://github.com/libarchive/libarchive/blob/v3.0.0a/libarchive/archive_write.c#L215"
    },
    {
      "type": "WEB",
      "url": "https://lists.debian.org/debian-lts-announce/2023/01/msg00034.html"
    },
    {
      "type": "WEB",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/V67OO2UUQAUJS3IK4JZPF6F3LUCBU6IS"
    },
    {
      "type": "WEB",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/V67OO2UUQAUJS3IK4JZPF6F3LUCBU6IS"
    },
    {
      "type": "WEB",
      "url": "https://security.gentoo.org/glsa/202309-14"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-476"
    ],
    "severity": "CRITICAL",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2022-11-22T02:15:00Z"
  }
}