{
  "schema_version": "1.4.0",
  "id": "GHSA-5xjj-cf5g-659h",
  "modified": "2022-07-29T00:00:33Z",
  "published": "2022-07-27T00:00:46Z",
  "aliases": [
    "CVE-2021-33468"
  ],
  "details": "An issue was discovered in yasm version 1.3.0. There is a use-after-free in error() in modules/preprocs/nasm/nasm-pp.c.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-33468"
    },
    {
      "type": "WEB",
      "url": "https://github.com/yasm/yasm/issues/162"
    },
    {
      "type": "WEB",
      "url": "https://gist.github.com/Clingto/bb632c0c463f4b2c97e4f65f751c5e6d"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-416"
    ],
    "severity": "MODERATE",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2022-07-26T13:15:00Z"
  }
}