{
  "schema_version": "1.4.0",
  "id": "GHSA-7r7x-qw92-2ffh",
  "modified": "2024-11-09T00:30:41Z",
  "published": "2024-05-21T15:31:42Z",
  "aliases": [
    "CVE-2021-47308"
  ],
  "details": "In the Linux kernel, the following vulnerability has been resolved:\n\nscsi: libfc: Fix array index out of bound exception\n\nFix array index out of bound exception in fc_rport_prli_resp().",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:L"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-47308"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/0fe70c15f9435bb3c50954778245d62ee38b0e03"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/44651522941c623e20882b3b443f23f77de1ea8b"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/4921b1618045ffab71b1050bf0014df3313a2289"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/8511293e643a18b248510ae5734e4f360754348c"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/a4a54c54af2516caa9c145015844543cfc84316a"
    },
    {
      "type": "WEB",
      "url": "https://git.kernel.org/stable/c/b27c4577557045f1ab3cdfeabfc7f3cd24aca1fe"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-125"
    ],
    "severity": "MODERATE",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2024-05-21T15:15:18Z"
  }
}