{
  "schema_version": "1.4.0",
  "id": "GHSA-mw5r-3vx4-h9cp",
  "modified": "2022-05-24T19:02:27Z",
  "published": "2022-05-24T19:02:27Z",
  "aliases": [
    "CVE-2021-32613"
  ],
  "details": "In radare2 through 5.3.0 there is a double free vulnerability in the pyc parse via a crafted file which can lead to DoS.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-32613"
    },
    {
      "type": "WEB",
      "url": "https://github.com/radareorg/radare2/issues/18666"
    },
    {
      "type": "WEB",
      "url": "https://github.com/radareorg/radare2/issues/18667"
    },
    {
      "type": "WEB",
      "url": "https://github.com/radareorg/radare2/issues/18679"
    },
    {
      "type": "WEB",
      "url": "https://github.com/radareorg/radare2/commit/5e16e2d1c9fe245e4c17005d779fde91ec0b9c05"
    },
    {
      "type": "WEB",
      "url": "https://github.com/radareorg/radare2/commit/a07dedb804a82bc01c07072861942dd80c6b6d62"
    },
    {
      "type": "WEB",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1959939"
    },
    {
      "type": "WEB",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/W3LPB5VGCIA7WA55FSB3YZQFUGZKWD7O"
    },
    {
      "type": "WEB",
      "url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/Y3S7JB46PONPHXZHIMR2XDPLGJCN5ZIX"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-415",
      "CWE-416"
    ],
    "severity": "MODERATE",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2021-05-14T13:15:00Z"
  }
}