{
  "schema_version": "1.4.0",
  "id": "GHSA-585r-x79p-835g",
  "modified": "2022-05-17T02:49:49Z",
  "published": "2022-05-17T02:49:49Z",
  "aliases": [
    "CVE-2016-4989"
  ],
  "details": "setroubleshoot allows local users to bypass an intended container protection mechanism and execute arbitrary commands by (1) triggering an SELinux denial with a crafted file name, which is handled by the _set_tpath function in audit_data.py or via a crafted (2) local_id or (3) analysis_id field in a crafted XML document to the run_fix function in SetroubleshootFixit.py, related to the subprocess.check_output and commands.getstatusoutput functions, a different vulnerability than CVE-2016-4445.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2016-4989"
    },
    {
      "type": "WEB",
      "url": "https://github.com/fedora-selinux/setroubleshoot/commit/dda55aa50db95a25f0d919c3a0d5871827cdc40f"
    },
    {
      "type": "WEB",
      "url": "https://github.com/fedora-selinux/setroubleshoot/commit/e69378d7e82a503534d29c5939fa219341e8f2ad"
    },
    {
      "type": "WEB",
      "url": "https://access.redhat.com/errata/RHSA-2016:1293"
    },
    {
      "type": "WEB",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1346461"
    },
    {
      "type": "WEB",
      "url": "https://rhn.redhat.com/errata/RHSA-2016-1267.html"
    },
    {
      "type": "WEB",
      "url": "http://seclists.org/oss-sec/2016/q2/574"
    },
    {
      "type": "WEB",
      "url": "http://securitytracker.com/id/1036144"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-77"
    ],
    "severity": "HIGH",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2017-04-11T18:59:00Z"
  }
}