{
  "schema_version": "1.4.0",
  "id": "GHSA-4h33-v95w-8vh4",
  "modified": "2022-04-09T00:00:42Z",
  "published": "2022-04-03T00:01:04Z",
  "aliases": [
    "CVE-2020-25691"
  ],
  "details": "A flaw was found in darkhttpd. Invalid error handling allows remote attackers to cause denial-of-service by accessing a file with a large modification date. The highest threat from this vulnerability is to system availability.",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ],
  "affected": [],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2020-25691"
    },
    {
      "type": "WEB",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1893725"
    }
  ],
  "database_specific": {
    "cwe_ids": [
      "CWE-755"
    ],
    "severity": "HIGH",
    "github_reviewed": false,
    "github_reviewed_at": null,
    "nvd_published_at": "2022-04-01T23:15:00Z"
  }
}